#python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/test_01.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/test_01_mask.png --ckpt release_model/E2FGVI-CVPR22.pth
python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/test_02.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/test_02_mask.png --ckpt release_model/E2FGVI-CVPR22.pth
python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/test_03.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/test_03_mask.png --ckpt release_model/E2FGVI-CVPR22.pth
python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/test_04.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/test_04_mask.png --ckpt release_model/E2FGVI-CVPR22.pth
python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/test_05.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/test_05_mask.png --ckpt release_model/E2FGVI-CVPR22.pth
python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/west1.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/west1_mask.png --ckpt release_model/E2FGVI-CVPR22.pth
python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/west2.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/west2_mask.png --ckpt release_model/E2FGVI-CVPR22.pth
python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/west3.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/west3_mask.png --ckpt release_model/E2FGVI-CVPR22.pth
python test.py --model e2fgvi --video /home/wegatron/win-data/data/video_inpating/input/delogo_examples/west4.mp4 --mask /home/wegatron/win-data/data/video_inpating/input/delogo_examples/mask/west4_mask.png --ckpt release_model/E2FGVI-CVPR22.pth

